In [2]:
import copy,math
import numpy as np
import matplotlib.pyplot as plt


In [3]:
X_train  = np.array([[2104, 5, 1, 45],
                     [1416, 3, 2, 40],
                     [852, 2, 1, 35]])
Y_train = np.array([460, 232, 178])
X_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [7]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {Y_train.shape}, y Type:{type(Y_train)})")
print(Y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [8]:
#y = mx + c
# c 
b_init = 785.1811367994083
# m
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")


w_init shape: (4,), b_init type: <class 'float'>


In [10]:
def predict(x,w,b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i]*w[i]
        p = p +p_i
        p = p + b
    return p

In [12]:
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

result = predict(x_vec,w_init,b_init)
print(f"result = {result}")


x_vec shape (4,), x_vec value: [2104    5    1   45]
result = 2815.543408017633


In [14]:
def predict(x,w,b):
    p = np.dot(x,w)+b
    return p

In [16]:
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")


x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [21]:
def compute_cost(X,Y,w,b):
    m = X.shape[0]
    cost = 0.0
    for i in range (m):
        f_wb_i = np.dot(X[i],w) + b
        cost = cost + (f_wb_i - Y[i])**2
    cost = cost / (2*m)
    return cost

In [22]:
cost = compute_cost(X_train,Y_train,w_init,b_init)
print(f'Cost at optimal w  : {cost}')

Cost at optimal w  : 1.5578904428966628e-12
